import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import axios from 'axios';
import React from 'react';
import { Project } from '../../utils/types';

type ProjectsProps = {
  projects: Project[];
};

const Projects: NextPage<ProjectsProps> = ({ projects }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Projects</h1>

        <p className={styles.description}>
          These are some projects where I participated
        </p>

        <div className={styles.grid}>
          {projects.map((project: Project) => (
            <a
              key={project.id}
              href={`/projects/${project.id}`}
              className={styles.card}
            >
              <h2>{project.name}</h2>
              <p>{project.description}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Projects;

export const getServerSideProps = async () => {
  const { data } = await axios.get(
    'https://mycv-django-api-staging.herokuapp.com/projects/',
  );

  return {
    props: { projects: data.results },
  };
};
