/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Business
 */
export interface Business {
  /**
   *
   * @type {string}
   * @memberof Business
   */
  url?: string;
  /**
   *
   * @type {string}
   * @memberof Business
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Business
   */
  country?: string | null;
}
