/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CollaborationProject
 */
export interface CollaborationProject {
  /**
   *
   * @type {number}
   * @memberof CollaborationProject
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof CollaborationProject
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationProject
   */
  name: string;
}
