/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollaborationProject } from './collaboration-project';
import { CollaborationTechnology } from './collaboration-technology';
import { User } from './user';

/**
 *
 * @export
 * @interface Collaboration
 */
export interface Collaboration {
  /**
   *
   * @type {number}
   * @memberof Collaboration
   */
  id?: number;
  /**
   *
   * @type {User}
   * @memberof Collaboration
   */
  collaborator: User;
  /**
   *
   * @type {string}
   * @memberof Collaboration
   */
  startedAt?: string | null;
  /**
   *
   * @type {string}
   * @memberof Collaboration
   */
  endedAt?: string | null;
  /**
   *
   * @type {Array<CollaborationTechnology>}
   * @memberof Collaboration
   */
  collaborationTechnologies?: Array<CollaborationTechnology>;
  /**
   *
   * @type {CollaborationProject}
   * @memberof Collaboration
   */
  project: CollaborationProject;
}
