/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CollaborationTechnology
 */
export interface CollaborationTechnology {
  /**
   *
   * @type {number}
   * @memberof CollaborationTechnology
   */
  technologyId: number;
  /**
   *
   * @type {string}
   * @memberof CollaborationTechnology
   */
  technologySlug: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationTechnology
   */
  comment?: string | null;
  /**
   *
   * @type {string}
   * @memberof CollaborationTechnology
   */
  technologyName: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationTechnology
   */
  technologyContent: string;
}
