/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollaborationCollaboratorGroups } from './collaboration-collaborator-groups';
import { CollaborationCollaboratorUserPermissions } from './collaboration-collaborator-user-permissions';

/**
 *
 * @export
 * @interface CollaborationCollaborator
 */
export interface CollaborationCollaborator {
  /**
   *
   * @type {number}
   * @memberof CollaborationCollaborator
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  lastLogin?: string | null;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   * @type {boolean}
   * @memberof CollaborationCollaborator
   */
  isSuperuser?: boolean;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  email?: string;
  /**
   * Designates whether the user can log into this admin site.
   * @type {boolean}
   * @memberof CollaborationCollaborator
   */
  isStaff?: boolean;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   * @type {boolean}
   * @memberof CollaborationCollaborator
   */
  isActive?: boolean;
  /**
   *
   * @type {string}
   * @memberof CollaborationCollaborator
   */
  dateJoined?: string;
  /**
   *
   * @type {Array<CollaborationCollaboratorGroups>}
   * @memberof CollaborationCollaborator
   */
  groups?: Array<CollaborationCollaboratorGroups>;
  /**
   *
   * @type {Array<CollaborationCollaboratorUserPermissions>}
   * @memberof CollaborationCollaborator
   */
  userPermissions?: Array<CollaborationCollaboratorUserPermissions>;
}
