/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollaborationCollaborator } from './collaboration-collaborator';
import { CollaborationTechnologies } from './collaboration-technologies';

/**
 *
 * @export
 * @interface Collaboration
 */
export interface Collaboration {
  /**
   *
   * @type {number}
   * @memberof Collaboration
   */
  id?: number;
  /**
   *
   * @type {CollaborationCollaborator}
   * @memberof Collaboration
   */
  collaborator?: CollaborationCollaborator;
  /**
   *
   * @type {string}
   * @memberof Collaboration
   */
  startedAt?: string | null;
  /**
   *
   * @type {string}
   * @memberof Collaboration
   */
  endedAt?: string | null;
  /**
   *
   * @type {Array<CollaborationTechnologies>}
   * @memberof Collaboration
   */
  technologies?: Array<CollaborationTechnologies>;
}
