/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Business } from './business';

/**
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse200
   */
  count: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse200
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof InlineResponse200
   */
  previous?: string | null;
  /**
   *
   * @type {Array<Business>}
   * @memberof InlineResponse200
   */
  results: Array<Business>;
}
