/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Technology } from './technology';

/**
 *
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
  /**
   *
   * @type {number}
   * @memberof InlineResponse2005
   */
  count: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2005
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2005
   */
  previous?: string | null;
  /**
   *
   * @type {Array<Technology>}
   * @memberof InlineResponse2005
   */
  results: Array<Technology>;
}
