/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Technology } from './technology';

/**
 *
 * @export
 * @interface ProjectTechnology
 */
export interface ProjectTechnology {
  /**
   *
   * @type {number}
   * @memberof ProjectTechnology
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ProjectTechnology
   */
  comment?: string | null;
  /**
   *
   * @type {string}
   * @memberof ProjectTechnology
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ProjectTechnology
   */
  content: string;
  /**
   *
   * @type {Technology}
   * @memberof ProjectTechnology
   */
  technology: Technology;
}
