/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TechnologyParentCollaboration } from './technology-parent-collaboration';
import { TechnologyProject } from './technology-project';

/**
 *
 * @export
 * @interface TechnologyParent
 */
export interface TechnologyParent {
  /**
   *
   * @type {number}
   * @memberof TechnologyParent
   */
  id?: number;
  /**
   *
   * @type {Array<TechnologyProject>}
   * @memberof TechnologyParent
   */
  projects: Array<TechnologyProject>;
  /**
   *
   * @type {Array<TechnologyParentCollaboration>}
   * @memberof TechnologyParent
   */
  collaborations: Array<TechnologyParentCollaboration>;
  /**
   *
   * @type {string}
   * @memberof TechnologyParent
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof TechnologyParent
   */
  content?: string | null;
  /**
   *
   * @type {string}
   * @memberof TechnologyParent
   */
  slug: string;
  /**
   *
   * @type {Set<number>}
   * @memberof TechnologyParent
   */
  parents?: Set<number>;
}
