/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TechnologyCollaborationProject
 */
export interface TechnologyCollaborationProject {
  /**
   *
   * @type {number}
   * @memberof TechnologyCollaborationProject
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof TechnologyCollaborationProject
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof TechnologyCollaborationProject
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof TechnologyCollaborationProject
   */
  slug: string;
  /**
   *
   * @type {number}
   * @memberof TechnologyCollaborationProject
   */
  business?: number | null;
  /**
   *
   * @type {Set<number>}
   * @memberof TechnologyCollaborationProject
   */
  collaborations?: Set<number>;
  /**
   *
   * @type {Set<number>}
   * @memberof TechnologyCollaborationProject
   */
  technologies?: Set<number>;
}
