/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TechnologyCollaborationCollaborator } from './technology-collaboration-collaborator';
import { TechnologyCollaborationProject } from './technology-collaboration-project';

/**
 *
 * @export
 * @interface TechnologyCollaboration
 */
export interface TechnologyCollaboration {
  /**
   *
   * @type {number}
   * @memberof TechnologyCollaboration
   */
  id?: number;
  /**
   *
   * @type {TechnologyCollaborationCollaborator}
   * @memberof TechnologyCollaboration
   */
  collaborator?: TechnologyCollaborationCollaborator;
  /**
   *
   * @type {TechnologyCollaborationProject}
   * @memberof TechnologyCollaboration
   */
  project?: TechnologyCollaborationProject;
}
