/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TechnologyProject } from './technology-project';
import { User } from './user';

/**
 *
 * @export
 * @interface TechnologyCollaboration
 */
export interface TechnologyCollaboration {
  /**
   *
   * @type {number}
   * @memberof TechnologyCollaboration
   */
  id?: number;
  /**
   *
   * @type {User}
   * @memberof TechnologyCollaboration
   */
  collaborator: User;
  /**
   *
   * @type {TechnologyProject}
   * @memberof TechnologyCollaboration
   */
  project: TechnologyProject;
}
