/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollaborationParents } from './collaboration-parents';
import { TechnologyCollaboration } from './technology-collaboration';
import { TechnologyProject } from './technology-project';

/**
 *
 * @export
 * @interface Technology
 */
export interface Technology {
  /**
   *
   * @type {number}
   * @memberof Technology
   */
  id?: number;
  /**
   *
   * @type {Array<TechnologyProject>}
   * @memberof Technology
   */
  projects: Array<TechnologyProject>;
  /**
   *
   * @type {Array<TechnologyCollaboration>}
   * @memberof Technology
   */
  collaborations: Array<TechnologyCollaboration>;
  /**
   *
   * @type {string}
   * @memberof Technology
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Technology
   */
  content?: string | null;
  /**
   *
   * @type {Array<CollaborationParents>}
   * @memberof Technology
   */
  parents?: Array<CollaborationParents>;
}
