/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TechnologyParentCollaboration
 */
export interface TechnologyParentCollaboration {
  /**
   *
   * @type {number}
   * @memberof TechnologyParentCollaboration
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof TechnologyParentCollaboration
   */
  collaborator: number;
  /**
   *
   * @type {number}
   * @memberof TechnologyParentCollaboration
   */
  project: number;
}
