/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { Business } from '../models';
// @ts-ignore
import { InlineResponse200 } from '../models';
/**
 * BusinessesApi - axios parameter creator
 * @export
 */
export const BusinessesApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * API endpoint that allows businesses to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    businessesList: async (
      page?: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/businesses/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * API endpoint that allows businesses to be viewed or edited.
     * @param {number} id A unique integer value identifying this business.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    businessesRead: async (
      id: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling businessesRead.',
        );
      }
      const localVarPath = `/businesses/{id}/`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * BusinessesApi - functional programming interface
 * @export
 */
export const BusinessesApiFp = function (configuration?: Configuration) {
  return {
    /**
     * API endpoint that allows businesses to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async businessesList(
      page?: number,
      options?: any,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse200>
    > {
      const localVarAxiosArgs = await BusinessesApiAxiosParamCreator(
        configuration,
      ).businessesList(page, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * API endpoint that allows businesses to be viewed or edited.
     * @param {number} id A unique integer value identifying this business.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async businessesRead(
      id: number,
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Business>
    > {
      const localVarAxiosArgs = await BusinessesApiAxiosParamCreator(
        configuration,
      ).businessesRead(id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * BusinessesApi - factory interface
 * @export
 */
export const BusinessesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * API endpoint that allows businesses to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    businessesList(
      page?: number,
      options?: any,
    ): AxiosPromise<InlineResponse200> {
      return BusinessesApiFp(configuration)
        .businessesList(page, options)
        .then(request => request(axios, basePath));
    },
    /**
     * API endpoint that allows businesses to be viewed or edited.
     * @param {number} id A unique integer value identifying this business.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    businessesRead(id: number, options?: any): AxiosPromise<Business> {
      return BusinessesApiFp(configuration)
        .businessesRead(id, options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for businessesList operation in BusinessesApi.
 * @export
 * @interface BusinessesApiBusinessesListRequest
 */
export interface BusinessesApiBusinessesListRequest {
  /**
   * A page number within the paginated result set.
   * @type {number}
   * @memberof BusinessesApiBusinessesList
   */
  readonly page?: number;
}

/**
 * Request parameters for businessesRead operation in BusinessesApi.
 * @export
 * @interface BusinessesApiBusinessesReadRequest
 */
export interface BusinessesApiBusinessesReadRequest {
  /**
   * A unique integer value identifying this business.
   * @type {number}
   * @memberof BusinessesApiBusinessesRead
   */
  readonly id: number;
}

/**
 * BusinessesApi - object-oriented interface
 * @export
 * @class BusinessesApi
 * @extends {BaseAPI}
 */
export class BusinessesApi extends BaseAPI {
  /**
   * API endpoint that allows businesses to be viewed or edited.
   * @param {BusinessesApiBusinessesListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BusinessesApi
   */
  public businessesList(
    requestParameters: BusinessesApiBusinessesListRequest = {},
    options?: any,
  ) {
    return BusinessesApiFp(this.configuration)
      .businessesList(requestParameters.page, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   * API endpoint that allows businesses to be viewed or edited.
   * @param {BusinessesApiBusinessesReadRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BusinessesApi
   */
  public businessesRead(
    requestParameters: BusinessesApiBusinessesReadRequest,
    options?: any,
  ) {
    return BusinessesApiFp(this.configuration)
      .businessesRead(requestParameters.id, options)
      .then(request => request(this.axios, this.basePath));
  }
}
