/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { Collaboration } from '../models';
// @ts-ignore
import { InlineResponse2001 } from '../models';
/**
 * CollaborationsApi - axios parameter creator
 * @export
 */
export const CollaborationsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * API endpoint that allows collaborations to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    collaborationsList: async (
      page?: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/collaborations/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * API endpoint that allows collaborations to be viewed or edited.
     * @param {number} id A unique integer value identifying this collaboration.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    collaborationsRead: async (
      id: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling collaborationsRead.',
        );
      }
      const localVarPath = `/collaborations/{id}/`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * CollaborationsApi - functional programming interface
 * @export
 */
export const CollaborationsApiFp = function (configuration?: Configuration) {
  return {
    /**
     * API endpoint that allows collaborations to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async collaborationsList(
      page?: number,
      options?: any,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2001>
    > {
      const localVarAxiosArgs = await CollaborationsApiAxiosParamCreator(
        configuration,
      ).collaborationsList(page, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * API endpoint that allows collaborations to be viewed or edited.
     * @param {number} id A unique integer value identifying this collaboration.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async collaborationsRead(
      id: number,
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Collaboration>
    > {
      const localVarAxiosArgs = await CollaborationsApiAxiosParamCreator(
        configuration,
      ).collaborationsRead(id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * CollaborationsApi - factory interface
 * @export
 */
export const CollaborationsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * API endpoint that allows collaborations to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    collaborationsList(
      page?: number,
      options?: any,
    ): AxiosPromise<InlineResponse2001> {
      return CollaborationsApiFp(configuration)
        .collaborationsList(page, options)
        .then(request => request(axios, basePath));
    },
    /**
     * API endpoint that allows collaborations to be viewed or edited.
     * @param {number} id A unique integer value identifying this collaboration.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    collaborationsRead(id: number, options?: any): AxiosPromise<Collaboration> {
      return CollaborationsApiFp(configuration)
        .collaborationsRead(id, options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for collaborationsList operation in CollaborationsApi.
 * @export
 * @interface CollaborationsApiCollaborationsListRequest
 */
export interface CollaborationsApiCollaborationsListRequest {
  /**
   * A page number within the paginated result set.
   * @type {number}
   * @memberof CollaborationsApiCollaborationsList
   */
  readonly page?: number;
}

/**
 * Request parameters for collaborationsRead operation in CollaborationsApi.
 * @export
 * @interface CollaborationsApiCollaborationsReadRequest
 */
export interface CollaborationsApiCollaborationsReadRequest {
  /**
   * A unique integer value identifying this collaboration.
   * @type {number}
   * @memberof CollaborationsApiCollaborationsRead
   */
  readonly id: number;
}

/**
 * CollaborationsApi - object-oriented interface
 * @export
 * @class CollaborationsApi
 * @extends {BaseAPI}
 */
export class CollaborationsApi extends BaseAPI {
  /**
   * API endpoint that allows collaborations to be viewed or edited.
   * @param {CollaborationsApiCollaborationsListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CollaborationsApi
   */
  public collaborationsList(
    requestParameters: CollaborationsApiCollaborationsListRequest = {},
    options?: any,
  ) {
    return CollaborationsApiFp(this.configuration)
      .collaborationsList(requestParameters.page, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   * API endpoint that allows collaborations to be viewed or edited.
   * @param {CollaborationsApiCollaborationsReadRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CollaborationsApi
   */
  public collaborationsRead(
    requestParameters: CollaborationsApiCollaborationsReadRequest,
    options?: any,
  ) {
    return CollaborationsApiFp(this.configuration)
      .collaborationsRead(requestParameters.id, options)
      .then(request => request(this.axios, this.basePath));
  }
}
