/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { InlineResponse2003 } from '../models';
// @ts-ignore
import { Manager } from '../models';
/**
 * ManagersApi - axios parameter creator
 * @export
 */
export const ManagersApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * API endpoint that allows managers to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    managersList: async (
      page?: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/managers/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * API endpoint that allows managers to be viewed or edited.
     * @param {number} id A unique integer value identifying this manager.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    managersRead: async (
      id: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling managersRead.',
        );
      }
      const localVarPath = `/managers/{id}/`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ManagersApi - functional programming interface
 * @export
 */
export const ManagersApiFp = function (configuration?: Configuration) {
  return {
    /**
     * API endpoint that allows managers to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async managersList(
      page?: number,
      options?: any,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2003>
    > {
      const localVarAxiosArgs = await ManagersApiAxiosParamCreator(
        configuration,
      ).managersList(page, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * API endpoint that allows managers to be viewed or edited.
     * @param {number} id A unique integer value identifying this manager.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async managersRead(
      id: number,
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Manager>
    > {
      const localVarAxiosArgs = await ManagersApiAxiosParamCreator(
        configuration,
      ).managersRead(id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * ManagersApi - factory interface
 * @export
 */
export const ManagersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * API endpoint that allows managers to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    managersList(
      page?: number,
      options?: any,
    ): AxiosPromise<InlineResponse2003> {
      return ManagersApiFp(configuration)
        .managersList(page, options)
        .then(request => request(axios, basePath));
    },
    /**
     * API endpoint that allows managers to be viewed or edited.
     * @param {number} id A unique integer value identifying this manager.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    managersRead(id: number, options?: any): AxiosPromise<Manager> {
      return ManagersApiFp(configuration)
        .managersRead(id, options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for managersList operation in ManagersApi.
 * @export
 * @interface ManagersApiManagersListRequest
 */
export interface ManagersApiManagersListRequest {
  /**
   * A page number within the paginated result set.
   * @type {number}
   * @memberof ManagersApiManagersList
   */
  readonly page?: number;
}

/**
 * Request parameters for managersRead operation in ManagersApi.
 * @export
 * @interface ManagersApiManagersReadRequest
 */
export interface ManagersApiManagersReadRequest {
  /**
   * A unique integer value identifying this manager.
   * @type {number}
   * @memberof ManagersApiManagersRead
   */
  readonly id: number;
}

/**
 * ManagersApi - object-oriented interface
 * @export
 * @class ManagersApi
 * @extends {BaseAPI}
 */
export class ManagersApi extends BaseAPI {
  /**
   * API endpoint that allows managers to be viewed or edited.
   * @param {ManagersApiManagersListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ManagersApi
   */
  public managersList(
    requestParameters: ManagersApiManagersListRequest = {},
    options?: any,
  ) {
    return ManagersApiFp(this.configuration)
      .managersList(requestParameters.page, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   * API endpoint that allows managers to be viewed or edited.
   * @param {ManagersApiManagersReadRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ManagersApi
   */
  public managersRead(
    requestParameters: ManagersApiManagersReadRequest,
    options?: any,
  ) {
    return ManagersApiFp(this.configuration)
      .managersRead(requestParameters.id, options)
      .then(request => request(this.axios, this.basePath));
  }
}
