/* tslint:disable */
/* eslint-disable */
/**
 * MyCV API
 * MyCV Django API
 *
 * The version of the OpenAPI document: v0.1
 * Contact: diogo.gomes77@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base';
// @ts-ignore
import { InlineResponse2005 } from '../models';
// @ts-ignore
import { Technology } from '../models';
/**
 * TechnologiesApi - axios parameter creator
 * @export
 */
export const TechnologiesApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * API endpoint that allows technologies to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    technologiesList: async (
      page?: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/technologies/`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
    /**
     * API endpoint that allows technologies to be viewed or edited.
     * @param {number} id A unique integer value identifying this technology.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    technologiesRead: async (
      id: number,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling technologiesRead.',
        );
      }
      const localVarPath = `/technologies/{id}/`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      if (configuration && (configuration.username || configuration.password)) {
        localVarRequestOptions['auth'] = {
          username: configuration.username,
          password: configuration.password,
        };
      }

      const queryParameters = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        queryParameters.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        queryParameters.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(queryParameters).toString();
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url:
          localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * TechnologiesApi - functional programming interface
 * @export
 */
export const TechnologiesApiFp = function (configuration?: Configuration) {
  return {
    /**
     * API endpoint that allows technologies to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async technologiesList(
      page?: number,
      options?: any,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2005>
    > {
      const localVarAxiosArgs = await TechnologiesApiAxiosParamCreator(
        configuration,
      ).technologiesList(page, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
    /**
     * API endpoint that allows technologies to be viewed or edited.
     * @param {number} id A unique integer value identifying this technology.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async technologiesRead(
      id: number,
      options?: any,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Technology>
    > {
      const localVarAxiosArgs = await TechnologiesApiAxiosParamCreator(
        configuration,
      ).technologiesRead(id, options);
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH,
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: (configuration?.basePath || basePath) + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * TechnologiesApi - factory interface
 * @export
 */
export const TechnologiesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * API endpoint that allows technologies to be viewed or edited.
     * @param {number} [page] A page number within the paginated result set.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    technologiesList(
      page?: number,
      options?: any,
    ): AxiosPromise<InlineResponse2005> {
      return TechnologiesApiFp(configuration)
        .technologiesList(page, options)
        .then(request => request(axios, basePath));
    },
    /**
     * API endpoint that allows technologies to be viewed or edited.
     * @param {number} id A unique integer value identifying this technology.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    technologiesRead(id: number, options?: any): AxiosPromise<Technology> {
      return TechnologiesApiFp(configuration)
        .technologiesRead(id, options)
        .then(request => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for technologiesList operation in TechnologiesApi.
 * @export
 * @interface TechnologiesApiTechnologiesListRequest
 */
export interface TechnologiesApiTechnologiesListRequest {
  /**
   * A page number within the paginated result set.
   * @type {number}
   * @memberof TechnologiesApiTechnologiesList
   */
  readonly page?: number;
}

/**
 * Request parameters for technologiesRead operation in TechnologiesApi.
 * @export
 * @interface TechnologiesApiTechnologiesReadRequest
 */
export interface TechnologiesApiTechnologiesReadRequest {
  /**
   * A unique integer value identifying this technology.
   * @type {number}
   * @memberof TechnologiesApiTechnologiesRead
   */
  readonly id: number;
}

/**
 * TechnologiesApi - object-oriented interface
 * @export
 * @class TechnologiesApi
 * @extends {BaseAPI}
 */
export class TechnologiesApi extends BaseAPI {
  /**
   * API endpoint that allows technologies to be viewed or edited.
   * @param {TechnologiesApiTechnologiesListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TechnologiesApi
   */
  public technologiesList(
    requestParameters: TechnologiesApiTechnologiesListRequest = {},
    options?: any,
  ) {
    return TechnologiesApiFp(this.configuration)
      .technologiesList(requestParameters.page, options)
      .then(request => request(this.axios, this.basePath));
  }

  /**
   * API endpoint that allows technologies to be viewed or edited.
   * @param {TechnologiesApiTechnologiesReadRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TechnologiesApi
   */
  public technologiesRead(
    requestParameters: TechnologiesApiTechnologiesReadRequest,
    options?: any,
  ) {
    return TechnologiesApiFp(this.configuration)
      .technologiesRead(requestParameters.id, options)
      .then(request => request(this.axios, this.basePath));
  }
}
